apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempchat
  labels:
    app: tempchat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempchat
  template:
    metadata:
      labels:
        app: tempchat
    spec:
      containers:
        - name: tempchat
          image: ghcr.io/kotcsolutions/tempchat:1.0.1
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: tempchat
spec:
  selector:
    app: tempchat
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
